### ISSUE TITLE
Libraries never load from remote server with PIN Auth

### ISSUE THREAD

**Issue by aaronstc1** [cglatot/pasta#15]
**Describe the bug**
When logged in with PIN Auth there are no libraries to choose from. (Have not attempted token method)

**To Reproduce**
1. Log in with PIN Auth
2. Click on remote server name under "Plex Servers"
3. Scroll down to "Plex Libraries"
4. There are no libraries

**Expected behavior**
Libraries should populate.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.116

**Comment by cglatot** [comment]
Hi @aaronstc1 - are you using the docker container, the site locally, or the site on pastatool.com?

If you're using the site pastatool.com, can you make sure you are on HTTP (not S) and try again?

**Comment by aaronstc1** [comment]
Was using pastatool.com and it does, in fact, work over HTTP.

**Comment by cglatot** [comment]
Ah ha, okay - this has been an ongoing problem, for which I don't think there is a workaround. However, I will add a redirect / message to http when trying to access a server this way. There is already a message on the URL / Token method, I thought that with PIN auth I might not need it anymore.
