### ISSUE TITLE
Select subtitle tracks on a per-season basis

### ISSUE THREAD

**Issue by harryt04** [cglatot/pasta#2]
**Is your feature request related to a problem? Please describe.**
Often times I will download shows on a per season basis, each season being from a different person or source. Because of this, each season will follow a different pattern of their subtitle track names, order, etc. 

**Describe the solution you'd like**
In addition to the existing functionality of selecting a subtitle track per episode or for an entire show, I'd love the ability to set a default subtitle track for a season of a tv show or anime.

**Comment by harryt04** [comment]
P.S. github won't let me select a "Feature Request" label to this github issue. I'm not sure if that's locked to non-collaborators, or if you don't have labels yet, but yeah.

**Comment by cglatot** [comment]
Ah yeah, I forgot to assign labels to the templates - good catch! Non-collaborators cannot add their own labels as far as I am aware, but the auto labels from templates should help.
