### ISSUE TITLE
Remembered settings are different between http and https

### ISSUE THREAD

**Issue by cglatot** [cglatot/pasta#20]
**Describe the bug**
localstorage counts the http and https sites as different locations, and thus login credentials are not shared across them.

**Expected behavior**
Remembered settings should be the same across http and https sites

**Comment by ukdtom** [comment]
Browse to PMS:32400/identity, and use the machineIdentifier as the ID to store it in

**Comment by ukdtom** [comment]
Or grap it from https://plex.tv/api/v2/resources and use clientIdentifier

**Comment by garretaserra** [comment]
Separating http and https versions of this or any website is a core principle to security.
The localstorage is not shared because it would be unsecure to do so.

**Comment by cglatot** [comment]
Yeah, I know it's intent, but my thinking was for convenience it would be useful to do something. But any method that would achieve this would either be hacky, or require a backend, which opens up its own set of security implications. Just going to close this one.
