### ISSUE TITLE
Support of Chinese Characters for TV Shows

### ISSUE THREAD

**Issue by Chalanxe** [cglatot/pasta#23]
**Is your feature request related to a problem? Please describe.**
TV Shows with Chinese characters are not displayed at all in the series tab(not in alphabet strip or #)

**Describe the solution you'd like**
All the unsupported languages/characters for tv shows could be displayed under the # section.

This might be a font/encoding problem(Japanese and Korean characters could be affected too)

**Comment by cglatot** [comment]
Solved in latest pull #31 

Thanks for raising this!
