### ISSUE TITLE
Can't Log in iOS

### ISSUE THREAD

**Issue by fakedname** [cglatot/pasta#33]
Nothing shows up for me when I try safari on iOS.  I have no issues logging in on the desktop version.  I tap on the Plex Login and Try the URL/Token and there is no change.  iOS 14.0.1 if that matters.

**Comment by fakedname** [comment]
I've also tried Chrome on iOS and same issue.

**Comment by cglatot** [comment]
Thanks for bringing this to my attention! I pushed a fix that should now show the proper login button. You might need to enable popups for PASTA (via browser settings) until I can get time to see if I can somehow force allow it. But it should at least work now.

**Comment by geraldbrent1** [comment]
Just checking in. Recently installed PASTA on my server, and I can’t login using Safari on iPadOS, despite any combination of browser settings.

**Comment by cglatot** [comment]
> Just checking in. Recently installed PASTA on my server, and I can’t login using Safari on iPadOS, despite any combination of browser settings.

Have you tried this? https://kb.nmsu.edu/page.php?id=79987

You may need to fully close and then reopen Safari.
If that doesn't work, please give me more information about what exactly happens when you try to login.
