### ISSUE TITLE
Check alternative HTTPS methods

### ISSUE THREAD

**Issue by cglatot** [cglatot/pasta#4]
**Describe the bug**
Currently you cannot always access a server via HTTPS because of the hash being added to the address. Need to find a method to work around this hash, or an alternative.

**Comment by cglatot** [comment]
This is probably not necessary anymore after #5 is resolved.

**Comment by cglatot** [comment]
With the other workarounds and warning messages available, this is not really an issue. I also do not think anything can be done about this due to the Plex REST API. If anyone knows how to interact with the API over strictly HTTPS, please let me know.

**Comment by ukdtom** [comment]
See https://github.com/cglatot/pasta/issues/25#issuecomment-703892611

**Comment by cglatot** [comment]
Fixed with release 1.6.0
