### ISSUE TITLE
Emby support/compatibility

### ISSUE THREAD

**Issue by stplatt** [cglatot/pasta#43]
Great tool for Plex but it would be great to use for Emby (https://emby.tv/) also.

It doesn't appear that a similar tool exists for Emby users

Will you consider adding support for Emby?

**Comment by bukkaroo** [comment]
I would love this! Moved from Plex to Emby a couple of years ago and I'd love to use Pasta.

**Comment by cglatot** [comment]
I'll need to have a look at the Emby APIs. Chances are I would need to make an entirely different tool / site for this, since PASTA was developed entirely around the flow of Plex APIs.

I currently have no plans for this, as I don't even have the time to enhance PASTA, but if I get more time in the future, then I will consider it.

**Comment by GlassedSilver** [comment]
Not sure if I should make a separate issue for this, but if the request could also be home to a humble Jellyfin request that'd be swell! :)

**Comment by cglatot** [comment]
Does Jellyfin not allow mass-updating tracks either?? What is it with media players and not allowing batch processing? :( 

Same answer as above - if I ever get some spare time and there isn't another good solution, I will see.

**Comment by GlassedSilver** [comment]
Media manager, a player is a player first and foremost, however you’d be mistaken for taking these as player since as you said yourself the level of metadata control is lackluster to say the least.

**Comment by cglatot** [comment]
Going to close this issue. From a quick search it looks like Emby might now have this feature? Not sure about Jellyfin.

In either case, I don't even have the time to manage PASTA, so anything new at this point is definitely beyond my scope.

The code is all on Github though, so if anyone finds it, they can take it and tweak it for Emby / Jellyfin.
