### ISSUE TITLE
Add Username / Password Authentication to Plex

### ISSUE THREAD

**Issue by cglatot** [cglatot/pasta#5]
**Describe the solution you'd like**
Rather than having to use the Plex Server URL and Plex-X-Token, we should be able to authenticate via username / password as this is more standard.

**Comment by cglatot** [comment]
Potential reference to look into: https://github.com/samcm/synclounge/blob/master/src/components/signin.vue#L57

**Comment by cglatot** [comment]
Decided to go with PIN authentication vs Username / Password as it seems a little more secure, and is an easier method to incorporate.

**Comment by Jomo94** [comment]
> 
> 
> Decided to go with PIN authentication vs Username / Password as it seems a little more secure, and is an easier method to incorporate.

You should consider getting the Username/Password option too imo. From a user stand point, logging in vs having to launch another page and copy the pin seems smoother. Plus it would match up better with existing side apps (like Ombi)

**Comment by cglatot** [comment]
> You should consider getting the Username/Password option too imo. From a user stand point, logging in vs having to launch another page and copy the pin seems smoother. Plus it would match up better with existing side apps (like Ombi)

Before I went the PIN route I was trying to get user / pass working, but I just couldn't get it. Documentation for REST based authentication and APIs for Plex are extremely lacking. But I'll reopen it and have another look in the future.

**Comment by ukdtom** [comment]
https://github.com/WebTools-NG/WebTools-NG/blob/master/src/store/modules/plextv.js#L102

**Comment by cglatot** [comment]
Thanks for that! That led me onto this, which seems to be the preferred method by Plex for authentication: https://forums.plex.tv/t/authenticating-with-plex/609370
