### ISSUE TITLE
Unknown Error (0) when accessing via URL

### ISSUE THREAD

**Issue by coralcarl** [cglatot/pasta#50]
I have a local server and I can connect per webapp over http without problems.

When I try via login the server shows up but I can't select a library and sometimes the server crashes.

Via URL/token on the http version I get an unknown error:
![image](https://user-images.githubusercontent.com/21178799/144750592-40f0aae0-169d-4265-84ca-e9a688519399.png)

**Comment by cglatot** [comment]
Hmm... That is an odd one. From the machine where you are trying to use PASTA, if you try going to http://192.168.0.178:32400 in a web browser, does that take you to plex okay?

**Comment by CoralCarl** [comment]
I have a server running on a RPi 4 and am using PASTA on my desktop. I can access the library perfectly fine with the address.

**Comment by cglatot** [comment]
> I can access the library perfectly fine with the address.

From the same desktop that you're trying to use PASTA?

If so, go to PASTA and bring up the Dev Tools (Ctrl + Shift + I on Chrome), go to the Network Tab. Right before you click on "Connect to Plex", at the top left of the Network tab click the "clear" button. (On Chrome it looks like a circle with a line through it)

 Click on "Connect to Plex" and then see if there are any errors in the network tab (they'll show up red).

Also check on the "Console" tab to check for any errors.

**Comment by CoralCarl** [comment]
It seems to be requesting via https regardless?
![image](https://user-images.githubusercontent.com/21178799/144751765-e52cb6da-0e7a-4f93-961e-aad85a539fc5.png)
![image](https://user-images.githubusercontent.com/21178799/144751773-ab345efe-afcc-4498-beb1-a7a913475403.png)

Console:
![image](https://user-images.githubusercontent.com/21178799/144751846-8f3a1e09-6d30-4c95-a519-53cad62114f3.png)

**Comment by cglatot** [comment]
Hmm, that is very strange. I just tried it over http and it worked fine, didn't try to go over https. Just to make sure, are you loading PASTA via http as well?

To go back to the main point, can you try the same thing with the network tab and the console tab when trying via the Login via Plex method instead of the token?

**Comment by CoralCarl** [comment]
Login is fine, still trying to request via secure connection. I am 100% on the http version. 
![image](https://user-images.githubusercontent.com/21178799/144753128-02a9de64-d461-4134-87a2-8089a38cb70d.png)

![image](https://user-images.githubusercontent.com/21178799/144753139-6736893e-bd3f-42ba-bdad-7d777e039bd0.png)

**Comment by CoralCarl** [comment]
So I just [deleted the domain security policy for PASTA](https://superuser.com/a/1493683), which appears to have fixed the forced https requests, still getting no response and an error though:
![image](https://user-images.githubusercontent.com/21178799/144753447-16c0dcf5-9803-4cec-90ab-a675b50eab81.png)

**Comment by lutjasuki** [comment]
Hi.

I've just started getting the same error in chrome

the console error is: (4) Ensure private network requests are made from secure contexts 
with four blocked requests listed "<html>
<body>


sections/ | blocked | Private | Public | insecure
-- | -- | -- | -- | --



</body>
</html>
"
I was able to get around the error by logging (via LAN address and token) using firefox instead (and making sure that the url for pastatool was http

**Comment by cglatot** [comment]
Hmmmm, yeah, Browsers are constantly updating to prevent insecure access and it's becoming a headache to try to maintain. If you untick the "Connect using local IP address" box it seems to work fine. Likewise, over https it works fine too.

I'll see if I can do something about the insecure local access, but I wouldn't hold my breath.

**Comment by Mindstorm1750** [comment]
This is not really a solution to the problem but a work around for users, if you are using chrome you can use this flag chrome://flags/#block-insecure-private-network-requests
and set it to disabled, but PLEASE once you are done put it back to default as it is a security issue if left disabled.

**Comment by ukdtom** [comment]
Could be wrong here, but my guess is that OP configured PMS to only accept secure connections, so a redirect to https will happen.

When doing so, PMS cert is issued to `xxxx.plex.direct` and not to an IP address, thus making the cert invalid, and that's what the code complains about

Ref: https://stackoverflow.com/questions/25723415/bypassing-ssl-certificate-error-in-jquery-and-ajax

**Below is not tested, since as already mentioned, I'm not a Pasta user, just stumbled across a Reddit thread, and then looked in the code ;)**

As a work around, OP could browse normally to https://app.plex.tv/

Then inspect a media, and show the xml
Ref: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

When looking at the XML page in the browser, it should show a valid url

![image](https://user-images.githubusercontent.com/4699449/206808461-15cdd0e8-0fbe-4fad-b13f-9c3a329ec9f1.png)

**Comment by slfight** [comment]
> Could be wrong here, but my guess is that OP configured PMS to only accept secure connections, so a redirect to https will happen.
> 
> When doing so, PMS cert is issued to `xxxx.plex.direct` and not to an IP address, thus making the cert invalid, and that's what the code complains about
> 
> Ref: https://stackoverflow.com/questions/25723415/bypassing-ssl-certificate-error-in-jquery-and-ajax
> 
> **Below is not tested, since as already mentioned, I'm not a Pasta user, just stumbled across a Reddit thread, and then looked in the code ;)**
> 
> Ref: Reddit Thread: https://www.reddit.com/r/PleX/comments/zh2r38/is_pastatool_not_working/
> 
> As a work around, OP could browse normally to https://app.plex.tv/
> 
> Then inspect a media, and show the xml Ref: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/
> 
> When looking at the XML page in the browser, it should show a valid url, that could be used instead of an IP address
> 
> ![image](https://user-images.githubusercontent.com/4699449/206808461-15cdd0e8-0fbe-4fad-b13f-9c3a329ec9f1.png)

Hello, I've tried this method and it doesn't work. I've also tried removing ":32400" and that also doesn't work. I'm using PastaTool via the same machine the server is on. I've also tried using another pc on the same network, same login, to fiddle but also can't access. 

I've tried restarting my computer, clearing cookies. Nothing works. I've tried 127.0.0.1 and I can access app.plex.tv that way but doing the same using this method also doesn't work on PastaTool. 

![Untitled](https://user-images.githubusercontent.com/15474190/206814338-367f8e20-3f00-4dae-b4de-df88aee0e7f7.png)

**Comment by sgtsquiggs** [comment]
I had the same error:

1. I initially put in the wrong URL.
2. It continued to use that URL regardless of what I input (verified via inspector). 

Refreshing the page fixed it for me.

**Comment by cglatot** [comment]
@coralcarl @slfight Is this still an issue?

I know this is a preeeetty old thread, but doing some cleanup and wanted to check before just outright closing the issue.
