### ISSUE TITLE
Ignore audio/subtitle format when fuzzy matching

### ISSUE THREAD

**Issue by SnoFox** [cglatot/pasta#52]
**Is your feature request related to a problem? Please describe.**
When PASTA is presented with a series that has an identical set of language tracks, but different by format, it will not match by language exclusively. This forces a user to edit by seasons when it differs through a series.

While this is a huge improvement over editing one-at-a-time from the Plex UI, it seems like it could be a minor change that could bring a huge quality of life improvement to users.

**Describe the solution you'd like**
When given audio/subtitle options that match a request in language/code but no other methods, it should switch to it anyway.
Perhaps make it an optional confirm step if the fuzzing is too fuzzy.

**Describe alternatives you've considered**
I am currently working around this by not using the "Entire series" option for the tool.

**Additional context**
The show I noticed this on has two seasons, both with dual audio tracks: English and Japanese. However, season 1 has "Japanese (AC3 Stereo)" while season 2 is "Japanese (AAC Stereo)"
![image](https://user-images.githubusercontent.com/37625/156495087-5fcd15ea-42d7-4e6b-8767-0173b09dd7b7.png)
![image](https://user-images.githubusercontent.com/37625/156495072-15a0dc06-6aff-48f9-89f8-a56a456d9690.png)

**Comment by cglatot** [comment]
The way I have the track / subtitle matching set up is that it will look at the name, title, language, and language code. In terms of it matching based on "format", it only does that if it's part of the Name, and it can't match on other fields (like Language and Language Code).

It will try to make a perfect match if it can, and if it can't it will go back and see which track matches the most criteria. With the last case scenario matching based on Language Name, or Language Code alone. So this should already be doing what you're asking for. I tested with several series as well that had different formats for the same language, and it does match them based on the other criteria.

**Comment by SnoFox** [comment]
Perhaps I'm I encountering a bug then?

The two example screenshots, these are from the same show, S1 and S2. The output leads me to believe the only two language codes are `eng` and `jpn`.

If I select "Entire Series" and pick any of the audio tracks on either season, it only changes that season on both the English and Japanese audio tracks.

I've just reproduced this on Firefox 99.0.1 and Vivaldi 5.2.2623.39, both on Windows 11 21H2.

**Comment by cglatot** [comment]
Closing this due to age of issue, unable to reproduce.

If this is till an issue, please let me know, and provide more details.
