### ISSUE TITLE
New Pasta Logo

### ISSUE THREAD

**Issue by hernandito** [cglatot/pasta#56]
What do you think of this as your header logo?

![Logo_Title_Large2](https://user-images.githubusercontent.com/787317/182981591-8aef2126-3066-49dd-9b73-ba0b5f3a3cfb.png)

**Comment by cglatot** [comment]
Wow, I really do like that logo, but I want to stick with the one I have. I think it better flows with the theme, and it was made for me by a friend, so I'd like to stick with that. I do appreciate you taking the time to make an alternative though!
