### ISSUE TITLE
Change subtitles of shows in Watchlist

### ISSUE THREAD

**Issue by BadCo-NZ** [cglatot/pasta#59]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
To be able to change the subtitles and audio streams of shows and movies in your watchlist.

**Describe alternatives you've considered**
PASTA currently works great, but my suggestion would improve my workflow. As I scroll through Plex looking for content, I add things I want to watch to my watchlist. It would then be easy to go to PASTA, directly to my watchlist and change the subtitles without having to remember and search for shows.

**Additional context**
That's about it.

**Comment by cglatot** [comment]
Going to close this, and track it as part of #35
