### ISSUE TITLE
Episodes has only 2 subtitles, neither is the "forced" one in plex

### ISSUE THREAD

**Issue by DuckersMcQuack** [cglatot/pasta#60]
**Describe the bug**
Won't choose "forced" subtitle as default

**To Reproduce**
Any anime with english, and english forced subtitles, it won't choose forced, as pasta only sees English "dialogue" or "sings and songs"

**Expected behavior**
Pasta reading each episode's subtitle and accurately let me choose the subtitle it actually offers.

**Screenshots**

![Screenshot_20230128_121941](https://user-images.githubusercontent.com/9039370/215263804-ea7fc88c-5d86-4c51-b1f5-25e53c4754e9.png)
![Screenshot_20230128_121953](https://user-images.githubusercontent.com/9039370/215263806-67b3699f-f44b-455a-9d6b-133f3813db33.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Steam deck with SteamOS 3.4.4
 - Browser [e.g. chrome, safari] Local player
 - Version [e.g. 22] Plex 1.61.1 | Unknown pasta version. Doesn't say. Just states as "unknown"

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cglatot** [comment]
The "signs & songs" _is_ the Forced subtitle.

However, there is a known problem with forcing Forced subtitles. Closing this issue as it's being tracked in #53
