### ISSUE TITLE
Set quality

### ISSUE THREAD

**Issue by lollilol** [cglatot/pasta#61]
On my plex server I sometimes have 2 files for the same item, for example one is in 4k and the other is in 1080p. In the hamburger menu of the item I can choose "Play version".

Per Default always the best quality is selected, but you can select another one and then it's saved to that item. I feel like this property is something similar to the already existing options in Pastatool. Can you maybe look into if you can also automatically set this property? Would be such a nice improvement.

**Comment by cglatot** [comment]
I had a look, and I don't think there is a way to set this. If someone knows how it can be done, please let me know. Closing for now.
