### ISSUE TITLE
Obey Forced/Default

### ISSUE THREAD

**Issue by ne0conquer** [cglatot/pasta#63]
Plex doesn't obey Forced or Default flags for subtitles or audio. PASTA tool is useful, but I still have to go through each series for each user.

It would be nice if there was a global "Obey Flags" button at the Library/Series/Season/Episode levels. If a file has no forced flags, it could fallback to default flags, and if no default flags, fallback to first audio or no subtitles.

I really just want Plex to obey the flags I worked hard to create for all of my series. Not sure if there's a better solution for this.

**Comment by cglatot** [comment]
This would be resolved via #35 and #53 

Closing this in favour of tracking on those 2 issues.
