### ISSUE TITLE
Docker container doesn't start

### ISSUE THREAD

**Issue by BobSleeuw** [cglatot/pasta#65]
**Describe the bug**
Pasta doesn't start, give an error.

**To Reproduce**
Use the exact docker-compose script as described on the page and start the container. You get the error 
`standard_init_linux.go:219: exec user process caused: exec format error`, and Pasta doesn't even get assigned the port and does not start.

**Expected behavior**
Pastatool starts.

**Screenshots**
![image](https://github.com/cglatot/pasta/assets/75915110/87267ea7-4531-412b-8d7e-aa07049d3819)

**Desktop (please complete the following information):**
 - OS: Ubuntu, using Docker-compose

**Additional context**

**Comment by cglatot** [comment]
This seems more like an issue with Docker / environment than it does PASTA. Building fine for me on Windows and Unraid.

https://beebom.com/how-fix-exec-user-process-caused-exec-format-error-linux/

**Comment by BobSleeuw** [comment]
I have had no other issues with any other docker container on Ubuntu, this is the first one that refuses to even start.
