### ISSUE TITLE
Change automatically to new content

### ISSUE THREAD

**Issue by Ap0ph1s-W4ite** [cglatot/pasta#66]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The tool at the moment is not too much intuitive. It would be nice to select the same language for all libraries or when a series was added, at the first episode we select the right track and then PASTA will change to future episodes and always look to new episodes to change them.

**Comment by cglatot** [comment]
There's already a tool for this:

https://github.com/RemiRigal/Plex-Auto-Languages
