### ISSUE TITLE
Select multiple episodes using SHIFT and CTRL

### ISSUE THREAD

**Issue by T4C0B311** [cglatot/pasta#67]
Is your feature request related to a problem? Please describe.
Yes, it's related to an issue I am having. The Pasta Tool has been amazing for my anime library and really appreciate all your work!
Unfortunately within a season, there are episodes with different variations and amounts of subtitles. For Example, Episodes 1-50 Have one audio track and one subtitle language, whereas 50 onwards still have a single audio track but more than one subtitle track. With this, I'm running to an issue where I cannot save the setting for a whole season.

Describe the solution you'd like
I was thinking of allowing the selection of multiple episodes in the GUI, like clicking one episode and holding SHIFT to another episode selecting all episodes in between to be edited. Also the possibility of using CTRL to select multiple different episodes. I think it might be a nice addition if possible.

Describe alternatives you've considered
I was not able to find any alternative methods.

Additional context
Just wanted to say I really love the utility and thanks for your hard work!!!!

**Comment by cglatot** [comment]
If you use the "Single Season" and "Entire Series" toggles before choosing an audio or subtitle track then it will try to apply that to the entire season or series. It does this by trying to match based on a best match of subtitle details (Name, title, language, and code) - it tries to match most of them, then gets fuzzier and fuzzier. It doesn't always get everything, but should cover most cases.

Adding a shift/ctrl multiselect would not change the matching process and not make it more accurate, it would just limit for which episodes it would try this for. I may add it at a later date, but it's a low priority as it wouldn't really change the functionality.
