### ISSUE TITLE
Managed Users Not Updating

### ISSUE THREAD

**Issue by Ner0Tachiyomi** [cglatot/pasta#68]
**Describe the bug**
Just updated to the latest version of plex. Previous versions have worked just fine. I see that a couple years ago managed users were an issue. I'm assuming this was resolved because I've always been able to control the one managed user I have with pasta. Any time I would login to my plex server account and update it would update my main account audio / subtitles for both accounts.

This has changed since the last update and now the managed account is not longer updating with pasta. 

I've tried following the previous suggestions of getting the managed user tokens and logging in with those and I just get an error about trying to access a http server via the site in https. Then it redirects me to Plex Login as usual which doesn't help me since I can't manage my managed user that way anymore.  I can't even use my admin tokin to login, same error. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version 1.61.114

**SmartTV
 - Device: Chromecast w/ GoogleTV

**Comment by cglatot** [comment]
I never actually implemented the feature for managed accounts, so I'm not sure how you were able to do that previously! Maybe you were using a specific token for the managed account? There is some discussion about using tokens for managed users in #32 that you can try.
