### ISSUE TITLE
Subtitle order

### ISSUE THREAD

**Issue by Howchie** [cglatot/pasta#70]
**Describe the bug**
Plex now seems to order the subtitles with default subtitles at the top, regardless of the order in the file. Selecting a subtitle track in pastatool selects the corresponding position number in plex, not the actual track. The common example is in Anime files with sub tracks
1. English full
2. English signs and songs (default) 
3. Japanese

Selecting track 2 in pastatool actually plays track 1,because plex moves the default tracks to the top (as best as I can tell). Selecting track 1 in pastatool will use the default track, regardless of the name shown in the pastatool interface.

**Comment by cglatot** [comment]
Is this still an issue for you?

I tried this across multiple different anime and am unable to reproduce this. It selects the right tracks each time.

**Comment by Howchie** [comment]
No it seems to be resolved, must have been plex side.
