### ISSUE TITLE
Add to unraid CA

### ISSUE THREAD

**Issue by Roxedus** [cglatot/pasta#9]
I see you have a template for unraid. I can help you get it to CA.
* I can add it to our community driven repo trough https://github.com/selfhosters/unRAID-CA-templates/issues/155
* Or help you reach out tho the correct people on the unraid forums

**Comment by cglatot** [comment]
Sure @Roxedus - I'd be happy to go through the selfhosters repo. Do you want to add it? Or do you want me to do a PR?

**Comment by Roxedus** [comment]
As long as its added, it doesn't matter to me. a PR works for credibility

**Comment by cglatot** [comment]
Cool, I'll do a PR shortly then. Anything special I need to do, or just add it to the templates folder on https://github.com/selfhosters/unRAID-CA-templates/tree/master/templates ?

**Comment by Roxedus** [comment]
Thats pretty much it. You can also read this https://selfhosters.net/docker/templating/templating/#114-shave-off-the-xml

**Comment by cglatot** [comment]
Created PR selfhosters/unRAID-CA-templates#157
Thanks for reaching out :)
